### ISSUE TITLE
Research Multiasset pool

### ISSUE THREAD

**Issue by ryardley** [blockhackersio/zrclib#14]

**Comment by p0n1** [comment]
I've just completed and committed a minimal version of a multi-asset shielded pool. Please review the PR here: https://github.com/p0n1/tornado-nova/pull/1#issue-1669664756.

I'll be considering potential applications for this implementation, such as swaps or other features. However, it's possible that we may need to develop a more complex version of the multi-asset pool that supports different asset types within a single transaction.

**Comment by p0n1** [comment]
The zk-NFTs or shielded pool for ERC721 tokens seem to be easy to achieve because ERC-721 shares the same data structure as ERC-20.

**Comment by p0n1** [comment]
A privacy-protected swap feature can be easily implemented without modifying the circuit. We may only need to add two fields to the `ExtData` struct to support this functionality.

```solidity
  struct ExtData {
    address recipient;
    int256 extAmount;
    address relayer;
    uint256 fee;
    bytes encryptedOutput1;
    bytes encryptedOutput2;
    bool isL1Withdrawal;
    uint256 l1Fee;
    address swapToToken; // unshield -> swap via Uni or 0x -> re-shield to this token
    uint256 swapToAmount;
  }
```

The flow would be as follows: unshield (withdraw) tokens to a specific recipient (an external contract for swap), perform the swap using Uni or 0x, and, optionally, re-shield the swapped tokens into the pool. The swapToAmount can be set slightly lower than the market value to ensure that the user can create a valid proof in advance.

In this case, we can take advantage of the best liquidity available on the market. Since on-chain transfers are inevitable, it's acceptable to unshield the original token first. Thanks to the multi-asset shielded pool, users can re-shield back into the pool directly without involving one of their wallets.

**Comment by p0n1** [comment]
Completed the swap feature in https://github.com/p0n1/tornado-nova/pull/2

**Comment by eerkaijun** [comment]
Swap feature has been integrated.
